language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
- '6'
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: R8QK7RV+mGPEeJsQ8DZpu3ArNGGBL4F07wnBFQbbwA5zvMxlCFuXLb9qwAxhq1Gt6CCHI7dJN41aLIvLts1CVqVTjJMet6pyHoTiDoSK4L5cJdpWO+si8N6fvIAYipCypSJgDMb+Pee1Rxtdp4DXWUE/zaDl830k6fT9NYJ4hhsgnKU6VyCjFKOPJkArvyFo3x/8ac0yDPjlsTYc09ivW0iUneCveNrZsn4OHLz6tcBNcdgp7HXAZrtwcKiTIhbRxasjbKLlGAuCKZ4dM35ozKjTTvzTlq7lc5sfJb0aohVGAgV7gXCQ4qoiAeob79F4l2xWVVv1yABdV9ebA4fU2B7kuHLtcQifcbEaaZ3PxTrkLyPgxmrSfOxgNsw8HlXF3RpViW5KpdfaCWHQQvddWOpcpC0w4iNPnaov85Grob7PsfYnfqn4Bqv2/qGjSC/N/ArVBH/PPHd0TpQncDyo10M7Ioo7TVLCjo+jPpYnonwisiyL/C/QDlpE5RKlTrfMPq4/Z/5L4XB06RJOMTvTYF4HLDYuPr7EWdGKesHBvJMCoZj2jpJwEAhC7vWY0GAaoU/36nscELUQf+RXXVFSKx8/1GfRYjhlTHIOzcmKbf1ATY0HQdpSBH2w31G4fRiyoMyhUHR85IY/D/A+sof9BlbuML9hIOEHYRCkqoAiNAU=
