language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
- '6'
branches: 
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: kRgISFKM27H5pdV0DJgiJ56TH/EszkWEqKMJQciTqK/95EFGU8lBTjqC1zttBFd7ka8efmjswSVIoHmJ225V2lLIYy4rN6XU+92w1PVelOx1EUtq63z8+gCqn5RDprbYuDPNrZERtTNCkLJNxpn9GXdM2dy6GC/fHvMG2j2X+Bmiq9KkKTXJRb/zDhuVJncOBShNluq4T3VDdgafbbzN7U90ZQKDW5recBSutiSgtOvGuKVm3wgfCkqC0/wJjHI474ov/B+ZDe6okqd1Dq9zjnQEbFGZCFAl1cVOGitdADRIT34mX7ZZ3IpIsuJpZSdW83o44p8c6P0j95Ry5fYkDtPmuWpUvyh3PuZzb2UgGI3YT7FxwamJ1nRhgoXhnJOoWSuUPrV3/MbV7uhjAE36cHChhiwNKP15I9xsSkHK0Rp1NO847IEPZZBL0C+G+7dTJIZrjF+gzejXqah7zYlgsvw2FmWr89bfiAzDisP2UF90f26grPjTq/qS0SzxU1/nzyw0k0VADmjpqK67kovn0leF98xVp9BBPO42DmAp3dWM8lgGRmFGexcwkr0ugTQ3KunZImYYB428ifIpxlvOuoym86JZaN7csHUGhZt3/aKkv6Zy5iabMiO5FJ9zlH8xXFj7uivzmaKm1FozXI0SdkrzL9TfuxmilBLKNVPOd4M=
  - secure: R8QK7RV+mGPEeJsQ8DZpu3ArNGGBL4F07wnBFQbbwA5zvMxlCFuXLb9qwAxhq1Gt6CCHI7dJN41aLIvLts1CVqVTjJMet6pyHoTiDoSK4L5cJdpWO+si8N6fvIAYipCypSJgDMb+Pee1Rxtdp4DXWUE/zaDl830k6fT9NYJ4hhsgnKU6VyCjFKOPJkArvyFo3x/8ac0yDPjlsTYc09ivW0iUneCveNrZsn4OHLz6tcBNcdgp7HXAZrtwcKiTIhbRxasjbKLlGAuCKZ4dM35ozKjTTvzTlq7lc5sfJb0aohVGAgV7gXCQ4qoiAeob79F4l2xWVVv1yABdV9ebA4fU2B7kuHLtcQifcbEaaZ3PxTrkLyPgxmrSfOxgNsw8HlXF3RpViW5KpdfaCWHQQvddWOpcpC0w4iNPnaov85Grob7PsfYnfqn4Bqv2/qGjSC/N/ArVBH/PPHd0TpQncDyo10M7Ioo7TVLCjo+jPpYnonwisiyL/C/QDlpE5RKlTrfMPq4/Z/5L4XB06RJOMTvTYF4HLDYuPr7EWdGKesHBvJMCoZj2jpJwEAhC7vWY0GAaoU/36nscELUQf+RXXVFSKx8/1GfRYjhlTHIOzcmKbf1ATY0HQdpSBH2w31G4fRiyoMyhUHR85IY/D/A+sof9BlbuML9hIOEHYRCkqoAiNAU=
