language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
- '6'
branches:
except:
- /^v\d+\.\d+\.\d+$/
secure: "cSKzJG0wNpgo4isPGJVHa678B7jYFdch/a2mGpPDchontE+KoTvguM82lPNgxdU1GR8cMLpjZ47YVci4D1BttOgSAAm0pT656/RriZmNyeT57DU1LLZzYn/TeIys7O4RVJjP4qhaizx8ZqgTRkulstGGClPnhpxAHhyWMFTtKK6nFq/hc5m3IwMUW7STqISSgeBdUQKWCjQLRqyU9dz85bz5wC/U7dALkN2jbAkS6pljOcYFAIk6sGy/ZvMiZx7RD/y6QyrP9rVDuB1cK+G+cL1omAuk46cH5AQl8TPqMT8oCAJB5e5bqQ3SoDXkYdY22WDOnIqZ25LvU4hgPKE+IrtCbVDzgCJf4/vV40RhOyX/Q/JRBwT0Wcc42sTTNMsRuXdyBxVX6T80Qd50XER6w3vTtRPmBQXupPhLQvPp9R9atFLP9mX3P/wFZkOxpIBj8MhnmxmL2TpUbG699/rBhatcCEzrtLDJ6y2/Zk4ZDEu/d0427gT/wen35NGz3mRI5Dk2M/57ovdMUU9zkXURy4nexTBCfqpJ2ITQn49snWsFBJv9F5AAh7cK0AeytB6KUuAiNbpcIX0UgQp1r/IRcnoB3SkUzmpsipWaxEW66WyQ5U2qjV8+mAHC6Q36BcCrNLfo6u/+jD3TsjXzO3J1Wa7Zy81VZQm6rF3r7W0K2q0="